spring:
  datasource:
    primary:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/och_evcard_serv?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowMultiQueries=true
      username: root
      password: root
    secondary:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://192.162.1.229:3306/och_dev?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowMultiQueries=true
      username: root
      password: 123456

mybatis:
  type-aliases-package: com.example.**.domain
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:/com/example/demo/**/dao/mapping/*Mapper.xml