spring:
  datasource:
    primary:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/och_evcard_serv?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: -1
      validation-query: SELECT 'x'
      validation-query-timeout: 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 6000
      min-evictable-idle-time-millis: 1800000
    secondary:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.162.1.229:3306/och_dev?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: -1
      validation-query: SELECT 'x'
      validation-query-timeout: 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 6000
      min-evictable-idle-time-millis: 1800000

mybatis:
  type-aliases-package: com.example.**.domain
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:mapping/*Mapper.xml